services:
  etl:
    build: .
    ports:
      - 5000:5000
    environment:
      - BENTO_UID
      - BENTO_DEBUG=False
      - CORS_ORIGINS="*"
      - BENTO_AUTHZ_SERVICE_URL=""
      - BENTO_AUTHZ_ENABLED=False
      - INTERNAL_PORT=5000
      # OPTIONAL: temp hack to authenticate with PCGL submission service
      - EXTRACTOR_BEARER_TOKEN
      # OPTIONAL: S3 extractor config
      - AWS_CONFIG_FILE="/etl/.aws/config"
      - AWS_SHARED_CREDENTIALS_FILE="/etl/.aws/credentials"
      - AWS_PROFILE="pcgl-dev"
      - S3_BUCKET # S3 bucket to use
    # Optional mount your ~/.aws and set AWS_PROFILE to use local S3 credentials
    # volumes:
    #   - ~/.aws:/etl/.aws
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:5000/service-info" ]
      timeout: 5s
      interval: 30s
      start_period: 75s
      start_interval: 5s

