services:
  etl:
    build: .
    ports:
      - 5000:5000
    environment:
      - BENTO_UID
      - BENTO_DEBUG=False
      - CORS_ORIGINS="*"
      - BENTO_AUTHZ_SERVICE_URL=""
      - BENTO_AUTHZ_ENABLED=False
      - INTERNAL_PORT=5000
      # OPTIONAL: temp hack to authenticate with PCGL submission service
      - EXTRACTOR_BEARER_TOKEN
      # OPTIONAL: S3 extractor configs
      - S3_ENDPOINT
      - S3_BUCKET
      - S3_REGION
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_VALIDATE_SSL
      - S3_USE_HTTPS
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:5000/service-info" ]
      timeout: 5s
      interval: 30s
      start_period: 75s
      start_interval: 5s

